### ISSUE TITLE
Missing .hpi file and manual install

### ISSUE THREAD

**Issue by JeremyColton** [shazam/pipeline-builder#1]
Hi,

I cloned this project and I don't see a *.hpi plugin file so I can't manually install it. Where do I find this file?

I am also nervous of a manual installation because there may be dependencies that this plugin needs that may conflict with existing plugins.

I don't see this project under the "Available" plugin tab in the "Manage Jenkins" link in my Jenkins v2.2.1 so an automated install is sadly not possible, correct?

Many thanks

**Comment by JeremyColton** [comment]
Solved - I cloned the repo and ran mvn to generate the .hpi file.

**Comment by danosipov** [comment]
Hi @JeremyColton - this project was never pushed to Jenkins plugin repository, so its not available for automated install. However a manual install should be straightforward - let me know if you encounter any problems, and they can be documented.

**Comment by JeremyColton** [comment]
Hi Dani, the "installation" instructions say "Download *.hpi plugin file" but what you really mean is "run mvn in the root folder to generate the *.hpi file".  Please update this in your instructions to prevent others from getting confused.  Many many thanks, it's a great plugin!

**Comment by danosipov** [comment]
The HPI file is also available on github:
https://github.com/shazam/pipeline-builder/releases
